# Generated by Django 4.1.1 on 2022-10-01 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Familia',
            new_name='Persona',
        ),
    ]
